version: "3.8"

services:
  # MongoDB (Community Edition)
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
    volumes:
      - ./mongo-data:/data/db

  # Back-end
  api:
    build:
      dockerfile: library-web-apis\Dockerfile
    environment:
      - "MongoDB:ConnectionString=mongodb://root:123@mongo:27017"
      - "MongoDB:DatabaseName=library"
      - "ASPNETCORE_ENVIRONMENT=Development"
    depends_on:
      - mongo

  # Front-end
  client:
    build:
      dockerfile: client\Dockerfile
    environment:
      - NODE_ENV=development 
    volumes:
      - ./client:/app
      # - /app/node_modules
      # - /app/.next
    depends_on:
      - api

  # Reverse Proxy
  nginx:
    image: nginx:1.27.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - "80:80"
    depends_on:
      - api
      - client

